spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.0.9:5432/bill_service_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /bills
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30