spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.0.6:5432/deposit_service_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  #rabbitmq:
    #port: 5672
    #host:  localhost
    #username: guest
    #password: guest
    #listener:
      #direct:
        #default-requeue-rejected: true
  kafka:
    #Перечисление всех брокеров
    bootstrap-servers: host.docker.internal:29092,host.docker.internal:29093
    producer:
      #Настройка сериализации сообщений
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: com.example.deposit.*
      spring.json.type.mapping: depositDTO:com.example.deposit.dto.DepositResponseDTO


server:
  port: 8083

kafka:
  topics:
    test-topic: topic1

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30