spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:8001
      discovery:
        enabled: false
        service-id: config-server
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        #Регистрация notifier-service
        - id: account-service
          uri: http://localhost:8081/
          predicates:
            - Path=/accounts/**
        - id: bill-service
          uri: http://localhost:8082/
          predicates:
            - Path=/bills/**
        - id: deposit-service
          uri: http://localhost:8083/
          predicates:
            - Path=/deposits/**


server:
  port: 8989

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30