server:
  port: 9999

spring:
  rabbitmq:
    port: 5672
    host:  rabbitmq
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30