spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  profiles:
    active: native
  security:
    user:
      password: admin

server:
  port: 8001

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka